colors:
  # Default colors
  primary:
    background: "#24273a"
    foreground: "#cad3f5"

    dim_foreground: "#cad3f5"
    bright_foreground: "#cad3f5"

  # Cursor colors
  cursor:
    text: "#24273a"
    cursor: "#cad3f5"
  vi_mode_cursor:
    text: "#24273a"
    cursor: "#a6da95"

  # Search colors
  search:
    matches:
      foreground: "#24273a"
      background: "#181926"
    focused_match:
      foreground: "#24273a"
      background: "#a6da95"
    footer_bar:
      foreground: "#24273a"
      background: "#181926"

  # Selection colors
  selection:
    text: "#24273a"
    background: "#eed49f"

  # Normal colors
  normal:
    black: "#181926"
    red: "#ed8796"
    green: "#a6da95"
    yellow: "#eed49f"
    blue: "#8aadf4"
    magenta: "#b7bdf8"
    cyan: "#8bd5ca"
    white: "#cad3f5"

  # Bright colors
  bright:
    black: "#181926"
    red: "#ed8796"
    green: "#a6da95"
    yellow: "#eed49f"
    blue: "#8aadf4"
    magenta: "#b7bdf8"
    cyan: "#8bd5ca"
    white: "#cad3f5"

  # Dim colors
  dim:
    black: "#181926"
    red: "#ed8796"
    green: "#a6da95"
    yellow: "#eed49f"
    blue: "#8aadf4"
    magenta: "#b7bdf8"
    cyan: "#8bd5ca"
    white: "#cad3f5"
