#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' ''
                # bspc monitor ${monitor} -n "$name" -d '' '' '' ' ' '' '' '' ''

		let name++
	done
}

workspaces

bspc config border_width 3
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "#de8f78"
bspc config normal_border_color "#1e222a"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a 'VirtualBox Machine' desktop='^9' follow=on
bspc rule -a TelegramDesktop desktop='^6' follow=on
bspc rule -a code-oss desktop='^4' follow=on
bspc rule -a Microsoft-edge desktop='^2'
bspc rule -a Ymuse state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a copyq state=floating
bspc rule -a com.xunlei.download state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a uTools focus=on
bspc rule -a "VirtualBox Manager" state=floating

# 鼠标样式不应用桌面
xsetroot -cursor_name left_ptr 
polybar main &
nm-applet &
blueberry-tray & #蓝牙
exec mpd &
utools &
fcitx5 &
dunst &
picom &
flameshot &
xfce4-power-manager &
copyq &
nitrogen --restore &

# 12分钟自动锁屏
#xautolock -time 12 -locker "systemctl suspend" -detectsleep &
# remap
input-remapper-control --command autoload &
